import AppKit

@MainActor
final class ClipboardMonitor {
    private let pasteboard: NSPasteboard
    private let repository: ClipboardRepository
    private var timer: Timer?
    private var lastChangeCount: Int
    private var isObservingWorkspace = false

    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    init(repository: ClipboardRepository, pasteboard: NSPasteboard = .general) {
        self.repository = repository
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard !isObservingWorkspace else { return }
        isObservingWorkspace = true
        let notificationCenter = NSWorkspace.shared.notificationCenter
        notificationCenter.addObserver(
            self,
            selector: #selector(handleWorkspacePause),
            name: NSWorkspace.willSleepNotification,
            object: nil
        )
        notificationCenter.addObserver(
            self,
            selector: #selector(handleWorkspacePause),
            name: NSWorkspace.sessionDidResignActiveNotification,
            object: nil
        )
        notificationCenter.addObserver(
            self,
            selector: #selector(handleWorkspaceResume),
            name: NSWorkspace.didWakeNotification,
            object: nil
        )
        notificationCenter.addObserver(
            self,
            selector: #selector(handleWorkspaceResume),
            name: NSWorkspace.sessionDidBecomeActiveNotification,
            object: nil
        )
        resumeTimer()
    }

    private func resumeTimer() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(
            timeInterval: 2,
            target: self,
            selector: #selector(checkForChanges),
            userInfo: nil,
            repeats: true
        )
        timer.tolerance = 0.5
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func pauseTimer() {
        timer?.invalidate()
        timer = nil
    }

    func stop() {
        pauseTimer()
        NSWorkspace.shared.notificationCenter.removeObserver(self)
        isObservingWorkspace = false
    }

    @objc private func handleWorkspacePause() {
        pauseTimer()
    }

    @objc private func handleWorkspaceResume() {
        resumeTimer()
    }

    func markCurrentChangeHandled() {
        lastChangeCount = pasteboard.changeCount
    }

    @objc private func checkForChanges() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let rawTypes = Set((pasteboard.types ?? []).map(\.rawValue))
        guard ignoredTypes.isDisjoint(with: rawTypes) else { return }
        guard let capture = makeCapture() else { return }
        repository.record(capture)
    }

    private func makeCapture() -> ClipboardCapture? {
        let sourceApplication = NSWorkspace.shared.frontmostApplication
        let sourceName = sourceApplication?.localizedName ?? "未知应用"
        let sourceBundleID = sourceApplication?.bundleIdentifier ?? ""
        let capturedAt = Date()

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipboardCapture(
                type: .file,
                textContent: nil,
                imageData: nil,
                filePaths: paths,
                sourceAppName: sourceName,
                sourceBundleID: sourceBundleID,
                capturedAt: capturedAt
            )
        }

        if let imageData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           imageData.count <= 50 * 1_024 * 1_024 {
            return ClipboardCapture(
                type: .image,
                textContent: nil,
                imageData: imageData,
                filePaths: [],
                sourceAppName: sourceName,
                sourceBundleID: sourceBundleID,
                capturedAt: capturedAt
            )
        }

        if let urlString = pasteboard.string(forType: .URL), !urlString.isEmpty {
            return ClipboardCapture(
                type: .url,
                textContent: urlString,
                imageData: nil,
                filePaths: [],
                sourceAppName: sourceName,
                sourceBundleID: sourceBundleID,
                capturedAt: capturedAt
            )
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty,
           text.utf8.count <= 2 * 1_024 * 1_024 {
            return ClipboardCapture(
                type: .text,
                textContent: text,
                imageData: nil,
                filePaths: [],
                sourceAppName: sourceName,
                sourceBundleID: sourceBundleID,
                capturedAt: capturedAt
            )
        }

        return nil
    }
}
